/**
 * Default field set requested from the HUDOC query API. Matches the upstream
 * `echr-extractor` Python library so output is column-compatible.
 */
export const DEFAULT_FIELDS: ReadonlyArray<string> = [
  "itemid",
  "applicability",
  "appno",
  "article",
  "conclusion",
  "docname",
  "doctype",
  "doctypebranch",
  "ecli",
  "importance",
  "judgementdate",
  "languageisocode",
  "originatingbody",
  "violation",
  "nonviolation",
  "extractedappno",
  "scl",
  "publishedby",
  "representedby",
  "respondent",
  "separateopinion",
  "sharepointid",
  "externalsources",
  "issue",
  "referencedate",
  "rulesofcourt",
  "DocId",
  "WorkId",
  "Rank",
  "Author",
  "Size",
  "Path",
  "Description",
  "Write",
  "CollapsingStatus",
  "HighlightedSummary",
  "HighlightedProperties",
  "contentclass",
  "PictureThumbnailURL",
  "ServerRedirectedURL",
  "ServerRedirectedEmbedURL",
  "ServerRedirectedPreviewURL",
  "FileExtension",
  "ContentTypeId",
  "ParentLink",
  "ViewsLifeTime",
  "ViewsRecent",
  "SectionNames",
  "SectionIndexes",
  "SiteLogo",
  "SiteDescription",
  "deeplinks",
  "SiteName",
  "IsDocument",
  "LastModifiedTime",
  "FileType",
  "IsContainer",
  "WebTemplate",
  "SecondaryFileExtension",
  "docaclmeta",
  "OriginalPath",
  "EditorOWSUSER",
  "DisplayAuthor",
  "ResultTypeIdList",
  "PartitionId",
  "UrlZone",
  "AAMEnabledManagedProperties",
  "ResultTypeId",
  "rendertemplateid",
];

export const HUDOC_BASE_URL = "https://hudoc.echr.coe.int";

/** HUDOC document conversion endpoint for full text retrieval. */
export const HUDOC_DOCUMENT_URL = (itemId: string): string =>
  `${HUDOC_BASE_URL}/app/conversion/docx/html/body?library=ECHR&id=${encodeURIComponent(
    itemId,
  )}`;
